<?php


namespace app\admin\controller;

use think\Db;

use think\Controller;

class Baseadmin extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (!session('server')) {
            return $this->redirect($this->admPath . '/login/login');
        }
    }
}